# Generated by Django 3.1.7 on 2021-05-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryNutrientsData',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='active', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_create')),
                ('modifield_at', models.DateTimeField(auto_now=True, db_column='dt_modify')),
                ('greens', models.CharField(db_column='greens', max_length=32)),
            ],
            options={
                'verbose_name': 'Historico de Nutriente',
                'verbose_name_plural': 'Historico de Nutrientes',
                'db_table': 'historico_nutrientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LettuceNutrients',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='active', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_create')),
                ('modifield_at', models.DateTimeField(auto_now=True, db_column='dt_modify')),
                ('status_code', models.CharField(db_column='status_code', default='0', max_length=4)),
                ('ph_value', models.FloatField(db_column='ph_value', default='-1')),
                ('tds_value', models.FloatField(db_column='tds_value', default='-1')),
                ('tank_level', models.FloatField(db_column='tank_level', default='-1')),
            ],
            options={
                'verbose_name': 'Nutriente da Alface',
                'verbose_name_plural': 'Nutrientes das Alfaces',
                'db_table': 'nutrientes_alface',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManageModelBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryNutrientsDataManager',
            fields=[
                ('managemodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nutrient_state.managemodelbase')),
            ],
            bases=('nutrient_state.managemodelbase',),
        ),
        migrations.CreateModel(
            name='LettuceNutrientsManager',
            fields=[
                ('managemodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nutrient_state.managemodelbase')),
            ],
            bases=('nutrient_state.managemodelbase',),
        ),
    ]
