# Generated by Django 3.1.7 on 2021-03-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryNutrientsData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_create')),
                ('modifield_at', models.DateTimeField(auto_now=True, db_column='dt_modify')),
                ('greens', models.CharField(db_column='greens', max_length=32)),
            ],
            options={
                'verbose_name': 'Historico de Nutriente',
                'verbose_name_plural': 'Historico de Nutrientes',
                'db_table': 'historico_nutrientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LettuceNutrients',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_create')),
                ('modifield_at', models.DateTimeField(auto_now=True, db_column='dt_modify')),
                ('status_code', models.CharField(db_column='status_code', default='0000', max_length=4)),
                ('ph_value', models.FloatField(db_column='ph')),
            ],
            options={
                'verbose_name': 'Nutriente da Alface',
                'verbose_name_plural': 'Nutrientes das Alfaces',
                'db_table': 'nutreintes_alface',
                'managed': True,
            },
        ),
    ]
