# Generated by Django 3.1.7 on 2021-03-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient_state', '0002_auto_20210319_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historynutrientsdata',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lettucenutrients',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
